---
- hosts: all
  sudo: true
  vars:
    web_server: apachephp
    servername: agenciaxis.local www.agenciaxis.local 192.168.33.88
    timezone: America/Sao_Paulo
  vars_files:
    - vars/mysql.yml
    - vars/common.yml
    - [ "vars/apachephp.yml", "vars/ws_defaults.yml" ]
  roles:
    - init
    - php5-cli
    - apache
    - php5
    - mysql
    - phpcommon
    - php-pecl
    - composer
    - ruby
    - nodejs
    - yo
    - app
